export const addressesCopy = {
  listTitle: "Adreslerim",
  listLead: "Kayıtlı adresleriniz ödeme adımında otomatik doldurulur.",
  manageCta: "Adresleri yönet",
  empty: "Henüz kayıtlı adresiniz yok.",
  addCta: "Yeni adres ekle",
  backToAccount: "Hesabıma dön",
  defaultBadge: "Varsayılan",
  makeDefault: "Varsayılan yap",
  edit: "Düzenle",
  remove: "Sil",
  removeConfirm: "Bu adresi silmek istediğinize emin misiniz?",
  newTitle: "Yeni adres",
  editTitle: "Adresi düzenle",
  titleLabel: "Adres başlığı",
  titlePlaceholder: "Ev, İş…",
  fullNameLabel: "Ad Soyad",
  phoneLabel: "Telefon",
  addressLabel: "Adres",
  cityLabel: "İl",
  districtLabel: "İlçe",
  postalCodeLabel: "Posta kodu (isteğe bağlı)",
  save: "Kaydet",
  saving: "Kaydediliyor…",
  cancel: "Vazgeç",
  invalidInput: "Lütfen bilgileri kontrol edin.",
  titleRequired: "Adres başlığı girin.",
  nameRequired: "Ad ve soyadınızı girin.",
  phoneRequired: "Telefon numaranızı girin.",
  addressRequired: "Adresinizi girin.",
  cityRequired: "İl girin.",
  districtRequired: "İlçe girin.",
  tooMany: "En fazla 10 adres kaydedebilirsiniz. Yeni adres için birini silin.",
  notFound: "Adres bulunamadı.",
};
