export const adminCopy = {
  panelName: "Yönetim Paneli",
  navLabel: "Yönetim menüsü",
  backToStore: "Mağazaya dön",
  nav: {
    dashboard: "Panel",
    products: "Ürünler",
    tags: "Etiketler",
    sales: "İndirimler",
    inventory: "Stok",
    orders: "Siparişler",
    reviews: "Yorumlar",
    settings: "Ayarlar",
  },
  common: {
    save: "Kaydet",
    saving: "Kaydediliyor…",
    saved: "Kaydedildi.",
    cancel: "Vazgeç",
    delete: "Sil",
    edit: "Düzenle",
    create: "Oluştur",
    back: "Geri",
    invalidInput: "Lütfen bilgileri kontrol edin.",
    unauthorized: "Bu işlem için yetkiniz yok.",
    notFoundRow: "Kayıt bulunamadı.",
    genericError: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
  },
};

export const adminProductsCopy = {
  title: "Ürünler",
  newCta: "Yeni ürün",
  newTitle: "Yeni ürün",
  editTitle: (name: string) => `Ürünü düzenle: ${name}`,
  searchPlaceholder: "Ürün ara…",
  searchLabel: "Ürün ara",
  filterAll: "Tümü",
  filterPublished: "Yayında",
  filterDraft: "Taslak",
  empty: "Ürün bulunamadı.",
  variantCount: (count: number) => `${count} varyant`,
  stockTotal: (count: number) => `${count} adet stok`,
  statusLabels: { DRAFT: "Taslak", PUBLISHED: "Yayında" } as const,
  basicsHeading: "Temel bilgiler",
  nameLabel: "Ürün adı",
  slugLabel: "Slug",
  slugHint: "Mağaza adresinde görünür: /p/slug. Küçük harf ve tire kullanın.",
  descriptionLabel: "Açıklama",
  statusLabel: "Durum",
  featuredLabel: "Öne çıkan (ana sayfada gösterilir)",
  tagsHeading: "Etiketler",
  tagsHint: "Bir ürün birden çok etikete atanabilir.",
  tagsEmpty: "Önce etiket oluşturun.",
  flatTagsGroup: "Düz etiketler",
  optionsHeading: "Seçenekler",
  optionsHint:
    "Örn. Boya durumu, Boyut. Değer kombinasyonlarından varyantlar otomatik oluşturulur.",
  addOptionType: "Seçenek ekle",
  removeOptionType: "Seçeneği kaldır",
  optionNameLabel: "Seçenek adı",
  optionValuesLabel: "Değerler",
  addValue: "Değer ekle",
  removeValue: "Değeri kaldır",
  variantsHeading: "Varyantlar",
  variantsSingleHint: "Seçenek tanımlanmadı: ürün tek varyantla satılır.",
  variantDefaultLabel: "Standart",
  skuLabel: "SKU",
  priceLabel: "Fiyat (TL)",
  stockLabel: "Stok",
  activeLabel: "Satışta",
  noImagesWarning: "Bu üründe henüz görsel yok — en az bir görsel eklemeniz önerilir.",
  imagesAfterCreate: "Görselleri üründen sonra, düzenleme ekranından ekleyebilirsiniz.",
  nameRequired: "Ürün adı girin.",
  slugInvalid: "Slug yalnızca küçük harf, rakam ve tire içerebilir.",
  slugTaken: "Bu slug zaten kullanımda.",
  skuTaken: "Bu SKU zaten kullanımda.",
  invalidPrice: "Geçerli bir fiyat girin (örn. 149,90).",
  invalidStock: "Geçerli bir stok adedi girin.",
  optionNameRequired: "Seçenek adları boş olamaz ve tekrar edemez.",
  optionValueRequired: "Seçenek değerleri boş olamaz ve tekrar edemez.",
  variantMismatch: "Varyant listesi seçeneklerle uyuşmuyor. Sayfayı yenileyip tekrar deneyin.",
  notFound: "Ürün bulunamadı.",
  deleteConfirm: (name: string) =>
    `"${name}" ürünü silinsin mi? Sipariş geçmişindeki kayıtlar korunur, bu işlem geri alınamaz.`,
};

export const adminImagesCopy = {
  heading: "Görseller",
  uploadLabel: "Görsel dosyası",
  altInputLabel: "Alt metin (görselde ne var?)",
  uploadCta: "Görseli yükle",
  uploading: "Yükleniyor…",
  primaryBadge: "Kapak",
  setPrimary: "Kapak yap",
  moveUp: "Yukarı taşı",
  moveDown: "Aşağı taşı",
  deleteCta: "Sil",
  deleteConfirm: "Bu görsel silinsin mi?",
  altSave: "Alt metni kaydet",
  empty: "Henüz görsel yüklenmedi.",
  r2Missing:
    "Görsel deposu henüz yapılandırılmadı: .env dosyasındaki R2_* değişkenleri ayarlanınca yükleme açılır.",
  invalidFile: "Geçersiz dosya. JPEG, PNG veya WebP yükleyin (en fazla 10 MB).",
  altRequired: "Alt metin girin — erişilebilirlik için zorunludur.",
  uploadFailed: "Yükleme başarısız oldu. Lütfen tekrar deneyin.",
  notFound: "Görsel bulunamadı.",
};

export const adminTagsCopy = {
  title: "Etiketler",
  newCta: "Yeni etiket",
  newTitle: "Yeni etiket",
  editTitle: (name: string) => `Etiketi düzenle: ${name}`,
  hierarchicalHeading: "Hiyerarşik etiketler",
  flatHeading: "Düz etiketler",
  empty: "Henüz etiket yok.",
  productCount: (count: number) => `${count} ürün`,
  sortOrderShort: "Sıra",
  nameLabel: "Ad",
  slugLabel: "Slug",
  slugHint: "Mağaza adresinde görünür: /t/slug. Küçük harf ve tire kullanın.",
  typeLabel: "Tür",
  typeHierarchical: "Hiyerarşik (menüde görünür)",
  typeFlat: "Düz (filtre etiketi)",
  typeLockedHint: "Alt etiketleri olan bir etiketin türü değiştirilemez.",
  parentLabel: "Üst etiket (isteğe bağlı)",
  parentNone: "— Üst etiket yok —",
  parentLockedHint: "Alt etiketleri olan bir etikete üst etiket atanamaz.",
  sortOrderLabel: "Sıralama (küçük olan önce)",
  deleteConfirm: (name: string) =>
    `"${name}" etiketi silinsin mi? Etiket ürünlerden kaldırılır; ürünler silinmez.`,
  deleteBlockedChildren: "Önce alt etiketlerini silin veya taşıyın.",
  nameRequired: "Etiket adı girin.",
  slugInvalid: "Slug yalnızca küçük harf, rakam ve tire içerebilir.",
  slugTaken: "Bu slug zaten kullanımda.",
  parentInvalid: "Geçersiz üst etiket seçimi.",
  notFound: "Etiket bulunamadı.",
};

export const adminSalesCopy = {
  title: "İndirimler",
  newCta: "Yeni indirim",
  newTitle: "Yeni indirim",
  editTitle: (name: string) => `İndirimi düzenle: ${name}`,
  empty: "Henüz indirim yok.",
  statusPlanned: "Planlı",
  statusActive: "Aktif",
  statusEnded: "Bitti",
  statusEndedEarly: "Erken bitirildi",
  scopeSummary: (products: number, tags: number) => {
    const parts: string[] = [];
    if (products > 0) parts.push(`${products} ürün`);
    if (tags > 0) parts.push(`${tags} etiket`);
    return parts.join(" + ") || "Kapsam yok";
  },
  percentValue: (value: number) => `%${value}`,
  nameLabel: "İndirim adı",
  typeLabel: "İndirim türü",
  typePercent: "Yüzde (%)",
  typeFixed: "Sabit tutar (TL)",
  percentValueLabel: "İndirim yüzdesi (1–99)",
  fixedValueLabel: "İndirim tutarı (TL)",
  startsAtLabel: "Başlangıç (Türkiye saati)",
  endsAtLabel: "Bitiş (Türkiye saati)",
  scopeHeading: "Kapsam",
  scopeHint:
    "İndirim seçili ürünlere ve/veya etiketlere uygulanır. Üst etiket seçilirse alt etiketleri de kapsar; müşteri için en iyi fiyat kazanır.",
  scopeTags: "Etiketler",
  scopeProducts: "Ürünler",
  scopeProductsEmpty: "Henüz ürün yok.",
  endEarlyCta: "İndirimi şimdi bitir",
  endEarlyConfirm: (name: string) => `"${name}" indirimi şimdi bitirilsin mi?`,
  deleteConfirm: (name: string) => `"${name}" indirimi silinsin mi?`,
  nameRequired: "İndirim adı girin.",
  invalidPercent: "1 ile 99 arasında bir yüzde girin.",
  invalidFixed: "Geçerli bir indirim tutarı girin (örn. 50 veya 49,90).",
  invalidDates: "Geçerli başlangıç ve bitiş zamanı girin; bitiş başlangıçtan sonra olmalı.",
  scopeRequired: "En az bir ürün veya etiket seçin.",
  notFound: "İndirim bulunamadı.",
};

export const adminOrdersCopy = {
  title: "Siparişler",
  empty: "Sipariş bulunamadı.",
  filterAll: "Tümü",
  filterLabel: "Duruma göre filtrele",
  filterCta: "Filtrele",
  itemCount: (count: number) => `${count} kalem`,
  detailTitle: (orderNumber: string) => `Sipariş ${orderNumber}`,
  itemsHeading: "Ürünler",
  totalsHeading: "Tutarlar",
  subtotal: "Ara toplam",
  discount: "İndirim",
  shipping: "Kargo",
  shippingFree: "Ücretsiz",
  total: "Toplam",
  customerHeading: "Müşteri ve teslimat",
  nameLabel: "Ad Soyad",
  emailLabel: "E-posta",
  phoneLabel: "Telefon",
  addressLabel: "Adres",
  notesLabel: "Sipariş notu",
  paymentHeading: "Ödeme",
  providerLabel: "Yöntem",
  providerNames: { manual: "Havale / EFT", iyzico: "Kart (iyzico)" } as Record<string, string>,
  paymentRefLabel: "Ödeme referansı",
  invoiceDownload: "Faturayı indir (PDF)",
  placedAtLabel: "Sipariş tarihi",
  statusLabel: "Durum",
  confirmPaidCta: "Ödemeyi onayla (PAID)",
  confirmPaidHint:
    "Havale/EFT ödemesini hesapta doğruladıktan sonra onaylayın; stok bu adımda düşer.",
  confirmPaidConfirm: (orderNumber: string) =>
    `${orderNumber} ödemesi onaylansın mı? Stok düşecek ve işlem geri alınamaz.`,
  cancelCta: "Siparişi iptal et",
  cancelConfirm: (orderNumber: string) => `${orderNumber} iptal edilsin mi?`,
  alreadyTransitioned: "Sipariş durumu bu arada değişmiş. Sayfayı kontrol edin.",
  fulfillHeading: "Kargo",
  fulfillHint:
    "Kargo bilgilerini girip siparişi kargolandı olarak işaretleyin; müşteriye e-posta gönderilir. Alanlar isteğe bağlıdır.",
  carrierLabel: "Kargo firması (isteğe bağlı)",
  trackingNumberLabel: "Takip numarası (isteğe bağlı)",
  fulfillCta: "Kargolandı olarak işaretle",
  fulfillConfirm: (orderNumber: string) =>
    `${orderNumber} kargolandı olarak işaretlensin mi? Müşteriye kargo e-postası gönderilecek.`,
  cancelPaidCta: "Siparişi iptal et (iade manuel)",
  cancelPaidHint:
    "İptal, stokları geri yükler ve siparişi kapatır. ÜCRET İADESİNİ SİSTEM YAPMAZ — iyzico paneli veya havale ile iadeyi kendiniz yapmalısınız.",
  cancelPaidConfirm: (orderNumber: string) =>
    `${orderNumber} iptal edilsin mi? Stok geri yüklenecek. İADEYİ MANUEL YAPMANIZ GEREKİR.`,
  shippedAtLabel: "Kargoya verilme",
  carrierShortLabel: "Kargo firması",
  trackingShortLabel: "Takip numarası",
};

export const adminInventoryCopy = {
  title: "Stok",
  empty: "Henüz varyant yok.",
  lowStockNote: (threshold: number) =>
    `Stok ${threshold} adedin altına düşen varyantlar vurgulanır.`,
  productHeader: "Ürün",
  skuHeader: "SKU",
  priceHeader: "Fiyat",
  stockHeader: "Stok",
  lowBadge: "Düşük",
  inactiveBadge: "Satışta değil",
  draftBadge: "Taslak ürün",
  stockInputLabel: (product: string) => `${product} stok adedi`,
  save: "Kaydet",
  invalidStock: "Geçerli bir stok adedi girin.",
  notFound: "Varyant bulunamadı.",
};

export const adminSettingsCopy = {
  title: "Ayarlar",
  shippingHeading: "Kargo",
  flatShippingLabel: "Sabit kargo ücreti (TL)",
  freeThresholdLabel: "Ücretsiz kargo alt limiti (TL)",
  freeThresholdHint: "Bu tutar ve üzeri siparişlerde kargo ücretsiz olur.",
  inventoryHeading: "Stok",
  lowStockLabel: "Düşük stok eşiği (adet)",
  lowStockHint: "Stok bu adedin altına düşünce panelde ve stok ekranında vurgulanır.",
  paymentHeading: "Ödeme",
  manualEnabledLabel: "Havale / EFT ile ödemeyi aç",
  manualInstructionsLabel: "Havale / EFT talimatları",
  manualInstructionsHint:
    "Sipariş onay sayfasında gösterilir: banka, IBAN ve açıklama bilgilerini yazın.",
  taxHeading: "Vergi",
  kdvRateLabel: "KDV oranı (%)",
  kdvRateHint:
    "Fiyatlar KDV dahildir; bu oran yalnızca faturadaki KDV dökümünü belirler. Sipariş anındaki oran siparişe kaydedilir.",
  invalidMoney: "Geçerli bir tutar girin (örn. 149,90).",
  invalidThreshold: "Geçerli bir adet girin.",
  invalidKdvRate: "0–99 arası bir tam sayı girin.",
};

export const adminDashboardCopy = {
  title: "Panel",
  products: "Ürün",
  productsPublished: (published: number, draft: number) => `${published} yayında, ${draft} taslak`,
  activeSales: "Aktif indirim",
  lowStock: "Düşük stok",
  lowStockHint: (threshold: number) => `Eşik: ${threshold} adet altı`,
  pendingOrders: "Bekleyen sipariş",
  pendingOrdersHint: "Ödeme bekleyen siparişler",
  recentOrdersHeading: "Son siparişler",
  recentOrdersEmpty: "Henüz sipariş yok.",
  viewAll: "Tümünü gör",
};
