export const adminCopy = {
  panelName: "Yönetim Paneli",
  navLabel: "Yönetim menüsü",
  backToStore: "Mağazaya dön",
  nav: {
    dashboard: "Panel",
    products: "Ürünler",
    tags: "Etiketler",
    sales: "İndirimler",
    inventory: "Stok",
    orders: "Siparişler",
    settings: "Ayarlar",
  },
  common: {
    save: "Kaydet",
    saving: "Kaydediliyor…",
    saved: "Kaydedildi.",
    cancel: "Vazgeç",
    delete: "Sil",
    edit: "Düzenle",
    create: "Oluştur",
    back: "Geri",
    invalidInput: "Lütfen bilgileri kontrol edin.",
    unauthorized: "Bu işlem için yetkiniz yok.",
    notFoundRow: "Kayıt bulunamadı.",
    genericError: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
  },
};

export const adminTagsCopy = {
  title: "Etiketler",
  newCta: "Yeni etiket",
  newTitle: "Yeni etiket",
  editTitle: (name: string) => `Etiketi düzenle: ${name}`,
  hierarchicalHeading: "Hiyerarşik etiketler",
  flatHeading: "Düz etiketler",
  empty: "Henüz etiket yok.",
  productCount: (count: number) => `${count} ürün`,
  sortOrderShort: "Sıra",
  nameLabel: "Ad",
  slugLabel: "Slug",
  slugHint: "Mağaza adresinde görünür: /t/slug. Küçük harf ve tire kullanın.",
  typeLabel: "Tür",
  typeHierarchical: "Hiyerarşik (menüde görünür)",
  typeFlat: "Düz (filtre etiketi)",
  typeLockedHint: "Alt etiketleri olan bir etiketin türü değiştirilemez.",
  parentLabel: "Üst etiket (isteğe bağlı)",
  parentNone: "— Üst etiket yok —",
  parentLockedHint: "Alt etiketleri olan bir etikete üst etiket atanamaz.",
  sortOrderLabel: "Sıralama (küçük olan önce)",
  deleteConfirm: (name: string) =>
    `"${name}" etiketi silinsin mi? Etiket ürünlerden kaldırılır; ürünler silinmez.`,
  deleteBlockedChildren: "Önce alt etiketlerini silin veya taşıyın.",
  nameRequired: "Etiket adı girin.",
  slugInvalid: "Slug yalnızca küçük harf, rakam ve tire içerebilir.",
  slugTaken: "Bu slug zaten kullanımda.",
  parentInvalid: "Geçersiz üst etiket seçimi.",
  notFound: "Etiket bulunamadı.",
};

export const adminSettingsCopy = {
  title: "Ayarlar",
  shippingHeading: "Kargo",
  flatShippingLabel: "Sabit kargo ücreti (TL)",
  freeThresholdLabel: "Ücretsiz kargo alt limiti (TL)",
  freeThresholdHint: "Bu tutar ve üzeri siparişlerde kargo ücretsiz olur.",
  inventoryHeading: "Stok",
  lowStockLabel: "Düşük stok eşiği (adet)",
  lowStockHint: "Stok bu adedin altına düşünce panelde ve stok ekranında vurgulanır.",
  paymentHeading: "Ödeme",
  manualEnabledLabel: "Havale / EFT ile ödemeyi aç",
  manualInstructionsLabel: "Havale / EFT talimatları",
  manualInstructionsHint:
    "Sipariş onay sayfasında gösterilir: banka, IBAN ve açıklama bilgilerini yazın.",
  invalidMoney: "Geçerli bir tutar girin (örn. 149,90).",
  invalidThreshold: "Geçerli bir adet girin.",
};

export const adminDashboardCopy = {
  title: "Panel",
  products: "Ürün",
  productsPublished: (published: number, draft: number) => `${published} yayında, ${draft} taslak`,
  activeSales: "Aktif indirim",
  lowStock: "Düşük stok",
  lowStockHint: (threshold: number) => `Eşik: ${threshold} adet altı`,
  pendingOrders: "Bekleyen sipariş",
  pendingOrdersHint: "Ödeme bekleyen siparişler",
  recentOrdersHeading: "Son siparişler",
  recentOrdersEmpty: "Henüz sipariş yok.",
  viewAll: "Tümünü gör",
};
