export const authCopy = {
  loginTitle: "Giriş Yap",
  registerTitle: "Kayıt Ol",
  accountTitle: "Hesabım",
  emailLabel: "E-posta",
  passwordLabel: "Şifre",
  nameLabel: "Ad Soyad",
  loginSubmit: "Giriş yap",
  registerSubmit: "Kayıt ol",
  submitting: "Gönderiliyor…",
  continueWithGoogle: "Google ile devam et",
  orSeparator: "veya",
  noAccountPrompt: "Hesabınız yok mu?",
  haveAccountPrompt: "Zaten hesabınız var mı?",
  goToRegister: "Kayıt olun",
  goToLogin: "Giriş yapın",
  invalidCredentials: "E-posta veya şifre hatalı.",
  invalidInput: "Lütfen bilgileri kontrol edin.",
  invalidEmail: "Geçerli bir e-posta adresi girin.",
  nameTooShort: "Adınızı girin.",
  passwordTooShort: "Şifre en az 8 karakter olmalı.",
  emailTaken: "Bu e-posta ile bir hesap zaten var.",
  tooManyAttempts: "Çok fazla deneme yapıldı. Lütfen biraz sonra tekrar deneyin.",
  genericError: "Bir hata oluştu. Lütfen tekrar deneyin.",
  emailNotVerified:
    "E-posta adresiniz henüz doğrulanmadı. Gelen kutunuzu kontrol edin veya yeni bir bağlantı isteyin.",
  resendVerification: "Doğrulama bağlantısını tekrar gönder",
  linkSentGeneric: "Bu e-posta ile bir hesap varsa, bağlantı gönderildi.",
  noticeVerifySent:
    "Doğrulama bağlantısı e-posta adresinize gönderildi. Giriş yapmadan önce gelen kutunuzu kontrol edin.",
  noticeVerified: "E-posta adresiniz doğrulandı. Şimdi giriş yapabilirsiniz.",
  noticeResetDone: "Şifreniz güncellendi. Yeni şifrenizle giriş yapabilirsiniz.",
  forgotPasswordLink: "Şifremi unuttum",
  forgotTitle: "Şifremi Unuttum",
  forgotLead: "Hesabınızın e-posta adresini girin; şifre sıfırlama bağlantısı gönderelim.",
  forgotSubmit: "Bağlantı gönder",
  backToLogin: "Girişe dön",
  verifyPageTitle: "E-posta Doğrulama",
  verifyConfirmLead: "Hesabınızı etkinleştirmek için aşağıdaki düğmeye tıklayın.",
  verifyConfirmButton: "E-postamı doğrula",
  verifyInvalidTitle: "Bağlantı geçersiz",
  verifyInvalidBody:
    "Bu doğrulama bağlantısı geçersiz veya süresi dolmuş. Giriş sayfasından yeni bir bağlantı isteyebilirsiniz.",
  resetTitle: "Yeni Şifre Belirle",
  resetLead: "Hesabınız için yeni bir şifre girin.",
  newPasswordLabel: "Yeni şifre",
  resetSubmit: "Şifreyi güncelle",
  resetInvalidTitle: "Bağlantı geçersiz",
  resetInvalidBody:
    "Bu şifre sıfırlama bağlantısı geçersiz veya süresi dolmuş. Yeni bir bağlantı isteyebilirsiniz.",
  requestNewLink: "Yeni bağlantı iste",
  emailUnavailable: "Bu özellik şu anda kullanılamıyor. Lütfen bizimle iletişime geçin.",
  logout: "Çıkış yap",
  greeting: (name: string) => `Merhaba, ${name}`,
  ordersHeading: "Siparişlerim",
  ordersEmpty: "Henüz siparişiniz yok.",
  browseCta: "Ürünlere göz at",
};
