export const authCopy = {
  loginTitle: "Giriş Yap",
  registerTitle: "Kayıt Ol",
  accountTitle: "Hesabım",
  emailLabel: "E-posta",
  passwordLabel: "Şifre",
  nameLabel: "Ad Soyad",
  loginSubmit: "Giriş yap",
  registerSubmit: "Kayıt ol",
  submitting: "Gönderiliyor…",
  continueWithGoogle: "Google ile devam et",
  orSeparator: "veya",
  noAccountPrompt: "Hesabınız yok mu?",
  haveAccountPrompt: "Zaten hesabınız var mı?",
  goToRegister: "Kayıt olun",
  goToLogin: "Giriş yapın",
  invalidCredentials: "E-posta veya şifre hatalı.",
  invalidInput: "Lütfen bilgileri kontrol edin.",
  invalidEmail: "Geçerli bir e-posta adresi girin.",
  nameTooShort: "Adınızı girin.",
  passwordTooShort: "Şifre en az 8 karakter olmalı.",
  emailTaken: "Bu e-posta ile bir hesap zaten var.",
  tooManyAttempts: "Çok fazla deneme yapıldı. Lütfen biraz sonra tekrar deneyin.",
  genericError: "Bir hata oluştu. Lütfen tekrar deneyin.",
  logout: "Çıkış yap",
  greeting: (name: string) => `Merhaba, ${name}`,
  ordersHeading: "Siparişlerim",
  ordersEmpty: "Henüz siparişiniz yok.",
  browseCta: "Ürünlere göz at",
};
