export const checkoutCopy = {
  title: "Ödeme",
  contactHeading: "İletişim bilgileri",
  shippingHeading: "Teslimat adresi",
  fullNameLabel: "Ad Soyad",
  emailLabel: "E-posta",
  phoneLabel: "Telefon",
  addressLabel: "Adres",
  savedAddressesLegend: "Kayıtlı adresler",
  newAddressOption: "Yeni adres gir",
  saveAddressLabel: "Bu adresi adres defterime kaydet",
  cityLabel: "İl",
  districtLabel: "İlçe",
  postalCodeLabel: "Posta kodu (isteğe bağlı)",
  notesLabel: "Sipariş notu (isteğe bağlı)",
  paymentHeading: "Ödeme yöntemi",
  payWithCard: "Kart ile öde",
  payWithCardHint: "iyzico güvenli ödeme sayfasına yönlendirilirsiniz.",
  payManual: "Havale / EFT",
  payManualHint: "Sipariş sonrası ödeme talimatlarını göstereceğiz.",
  summaryHeading: "Sipariş özeti",
  subtotal: "Ara toplam",
  discount: "İndirim",
  shipping: "Kargo",
  shippingFree: "Ücretsiz",
  total: "Toplam",
  kdvNote: "Tüm fiyatlara KDV dahildir.",
  consentPreInfo: "Ön Bilgilendirme Formu",
  consentMiddle: "'nu ve ",
  consentContract: "Mesafeli Satış Sözleşmesi",
  consentSuffix: "'ni okudum, onaylıyorum.",
  consentRequired: "Devam etmek için sözleşmeleri onaylamanız gerekir.",
  submit: "Siparişi tamamla",
  submitting: "İşleniyor…",
  backToCart: "Sepete dön",
  emptyTitle: "Sepetiniz boş",
  emptyBody: "Ödeme adımına geçmek için sepetinize ürün ekleyin.",
  emptyCta: "Alışverişe başla",
  invalidInput: "Lütfen bilgileri kontrol edin.",
  nameRequired: "Ad ve soyadınızı girin.",
  invalidEmail: "Geçerli bir e-posta adresi girin.",
  phoneRequired: "Telefon numaranızı girin.",
  addressRequired: "Teslimat adresinizi girin.",
  cityRequired: "İl girin.",
  districtRequired: "İlçe girin.",
  cartChanged: "Sepetinizdeki bazı ürünlerin stok durumu değişti. Lütfen sepetinizi kontrol edin.",
  cartEmpty: "Sepetiniz boş.",
  noPaymentMethod: "Şu anda ödeme alınamıyor. Lütfen daha sonra tekrar deneyin.",
  paymentInitFailed: "Ödeme başlatılamadı. Lütfen tekrar deneyin.",
  paymentFailed: "Ödeme alınamadı. Bilgilerinizi kontrol edip tekrar deneyebilirsiniz.",
  tooManyAttempts: "Çok fazla deneme yapıldı. Lütfen biraz sonra tekrar deneyin.",
};

export const confirmationCopy = {
  title: "Siparişiniz alındı",
  paidLead: "Ödemeniz alındı, siparişiniz hazırlanıyor.",
  pendingLead: "Siparişiniz oluşturuldu ve ödemeniz bekleniyor.",
  orderNumberLabel: "Sipariş numarası",
  manualHeading: "Ödeme talimatları",
  manualFallback:
    "Havale/EFT bilgileri için bizimle iletişime geçin; ödemeniz onaylanınca siparişiniz hazırlanacak.",
  continueShopping: "Alışverişe devam et",
  notFoundTitle: "Sipariş bulunamadı",
  notFoundBody: "Bu bağlantı geçersiz veya siparişe erişim yetkiniz yok.",
};

export const accountOrdersCopy = {
  statusLabels: {
    PENDING_PAYMENT: "Ödeme bekleniyor",
    PAID: "Ödendi",
    CANCELLED: "İptal edildi",
    FULFILLED: "Kargolandı",
  } as const,
  trackingLine: (carrier: string, trackingNumber: string) => `${carrier} · ${trackingNumber}`,
  invoiceLink: "Faturayı indir (PDF)",
};
