export const emailCopy = {
  receivedSubject: (orderNumber: string) => `Siparişiniz alındı — ${orderNumber}`,
  paidSubject: (orderNumber: string) => `Ödemeniz alındı — ${orderNumber}`,
  receivedTitle: "Siparişiniz alındı",
  receivedLead:
    "Siparişiniz oluşturuldu. Ödemeniz onaylandığında siparişinizi hazırlamaya başlayacağız.",
  paidTitle: "Ödemeniz alındı",
  paidLead: "Ödemeniz onaylandı, siparişiniz hazırlanıyor.",
  greeting: (name: string) => `Merhaba ${name},`,
  orderNumberLabel: "Sipariş numarası",
  manualHeading: "Ödeme talimatları",
  manualFallback:
    "Havale/EFT bilgileri için bizimle iletişime geçin; ödemeniz onaylanınca siparişiniz hazırlanacak.",
  itemsHeading: "Sipariş özeti",
  quantityLabel: "Adet",
  subtotal: "Ara toplam",
  discount: "İndirim",
  shipping: "Kargo",
  shippingFree: "Ücretsiz",
  total: "Toplam",
  kdvNote: "Tüm fiyatlara KDV dahildir.",
  addressHeading: "Teslimat adresi",
  viewOrder: "Siparişi görüntüle",
  footerNote: "Bu e-posta, MofuTenshi hesabınız veya siparişinizle ilgili gönderilmiştir.",
  footerQuestions: "Sorunuz mu var? Bu e-postayı yanıtlayabilirsiniz.",
  shippedSubject: (orderNumber: string) => `Siparişiniz kargoya verildi — ${orderNumber}`,
  shippedTitle: "Siparişiniz kargoya verildi",
  shippedLead: "Siparişiniz yola çıktı. Aşağıdaki bilgilerle takip edebilirsiniz.",
  shippedLeadNoTracking: "Siparişiniz yola çıktı.",
  trackingHeading: "Kargo bilgileri",
  carrierLabel: "Kargo firması",
  trackingNumberLabel: "Takip numarası",
  verifySubject: "E-posta adresinizi doğrulayın — MofuTenshi",
  verifyTitle: "E-posta adresinizi doğrulayın",
  verifyLead:
    "MofuTenshi hesabınızı kullanmaya başlamak için e-posta adresinizi doğrulamanız gerekiyor.",
  verifyButton: "E-postamı doğrula",
  verifyExpiry: "Bu bağlantı 24 saat geçerlidir.",
  resetSubject: "Şifre sıfırlama bağlantınız — MofuTenshi",
  resetTitle: "Şifrenizi sıfırlayın",
  resetLead: "Hesabınız için yeni bir şifre belirlemek üzere aşağıdaki bağlantıyı kullanın.",
  resetButton: "Yeni şifre belirle",
  resetExpiry: "Bu bağlantı 1 saat geçerlidir.",
  notYouNote: "Bu isteği siz yapmadıysanız bu e-postayı yok sayabilirsiniz.",
};

// Owner-facing new-order notifications (R29.1).
export const adminEmailCopy = {
  placedSubject: (orderNumber: string) => `Yeni sipariş, ödeme bekleniyor — ${orderNumber}`,
  paidSubject: (orderNumber: string) => `Yeni sipariş, ödeme alındı — ${orderNumber}`,
  title: "Yeni sipariş",
  placedLead:
    "Havale/EFT ile yeni bir sipariş oluşturuldu. Ödeme geldiğinde admin panelinden onaylayın.",
  paidLead: "Kart ödemesi doğrulandı; sipariş hazırlanmaya hazır.",
  customerHeading: "Müşteri",
  viewInAdmin: "Siparişi admin panelinde aç",
};
